# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
 - package-ecosystem: "devcontainers"
   directory: "/"
   schedule:
     interval: weekly

name: TrabajoFinal  # Nombre del entorno

channels:

  - defaults  # Canal predeterminado

dependencies:

  - python=3.9  # Versión de Python

  - pandas=1.5.3  # Versión de pandas

  - numpy=1.24.2  # Versión de numpy

  - matplotlib=3.7.1  # Versión de matplotlib

  - pip  # Agregar pip para instalar paquetes con pip si es necesario

  - pip:

      - time  # Paquete 'time' se refiere al módulo estándar, no es necesario incluirlo